# Generated by Django 5.1.15 on 2026-09-17 02:25

import apps.common.encryption
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_billing_email'),
        ('settings_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('openrouter', 'OpenRouter')], max_length=20)),
                ('api_key', apps.common.encryption.EncryptedTextField(help_text='Org-supplied API key, encrypted at rest')),
                ('default_model', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('tested_at', models.DateTimeField(blank=True, null=True)),
                ('test_result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('untested', 'Untested')], default='untested', max_length=20)),
                ('test_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_configs', to='organizations.organization')),
            ],
            options={
                'db_table': 'settings_ai_provider_config',
                'unique_together': {('organization', 'provider')},
            },
        ),
    ]
