# Generated by Django 5.1.15 on 2026-09-17 02:13

import apps.common.encryption
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_add_devto_platform'),
        ('organizations', '0002_organization_billing_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('openrouter', 'OpenRouter')], max_length=20)),
                ('api_key', apps.common.encryption.EncryptedTextField()),
                ('model', models.CharField(help_text='e.g. gpt-4o-mini, claude-haiku-4-5-20251001, or an OpenRouter model id.', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text="Used when an AI action doesn't specify a provider override.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_configs', to='organizations.organization')),
            ],
            options={
                'db_table': 'credentials_ai_provider_config',
                'unique_together': {('organization', 'provider')},
            },
        ),
    ]
